language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: R5Ujw12vDWT9RTVZnjqmgoBeG8QgMdwKoShPHOEwnYOXIkxts5Qmg9+eCVoJRSYMZ2YMKk7sXisApKiOIhGv5PsJwIm1qXPlw6eQCWnnLE/OTJtoM0LgeKOcypwO28pJheHuHbd3jtCJ6eEKQiN1YPXSW2HTctYJU4a2ipgo8JY=
before_install:
  - npm install -g gulp
  - npm install 
  - gulp build
script: gulp test:saucelabs
