language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    username: jbalsas
    no_ssl_bump_domains: all
  jwt:
    secure: EGuJYJRW6X/XOJ3/feFGvNg64jcqjy6BAoCyhIUFBdazc/cE3hLhV8CpM+cUQcGPAUBCDAmr2uXKVtors9VhjH5uGX4mP5Gt3+eWutYZDEy0vtdBniLPV2YWAiiRlJkyx3jMUybV33GeV6MRN5s47K/RBINqYAJhajZl/6UKea2YFhC86J500TYSxYdH8kO+WTQaTMVgCR+KHscJYqMlqxqc/rCwHNWlTGr7Bu41FUbMxaUFlRI6pe6xRWa1DDzGPfeRsguos5y00QxEF4tUmcnvxKSfLHcgA1/RvMtUZVI9dErIwMScnOG6IegnpkP9JdGXpQdyjFrm8r8Wr0ooZN7yuCdIa2ySgk76crtgeKIvF44jijHvoV5YsM2kOuM74EzSKbjOOpIIZcfD8Si/KgRXeReZU9ngp1xR8PpBS3JCUubuw2zrexeHQInX6qJCrZi/5u4Z7j1gVPtO567gHQ+lptJE3WwVJe1Nk8s3r48h6IPfsodZUC8EP8BIF+jeADaNxhG/itkyHLAuYABb6202qiPBeMqqsm3RJwQcDs5IGTgHzmO0SNqmYHGZKBslzi9zs7eUWsH6yHQ/KRwSTRa0UFwxbUGf0seohYPsay3oQXY0HbIx4COY1p8oYo0qUa6WCT04irLtNGYIe+VxWwm1vuF48/VdZz1O9nz7UoY=
before_install:
  - npm install -g gulp
  - npm install 
  - gulp build
script: gulp test:saucelabs
